### ISSUE TITLE
Cannot install this package in lumen framework ^6.0

### ISSUE THREAD

**Issue by akkivarma** [vrajroham/laravel-flock-notification#5]
Hi, I am not able to install this package in v6 lumen framework. 

Getting below error:
```
Using version ^1.0 for vrajroham/laravel-flock-notification
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for illuminate/mail (locked at v6.20.16, required as ^6.0) -> satisfiable by illuminate/mail[v6.20.16].
    - Installation request for illuminate/notifications (locked at v6.20.41, required as ^6.0) -> satisfiable by illuminate/notifications[v6.20.41].
    - Installation request for vrajroham/laravel-flock-notification ^1.0 -> satisfiable by vrajroham/laravel-flock-notification[1.0.0, 1.0.1, 1.0.2, 1.0.3, v1.0.4, v1.0.4.x-dev, v1.0.5].
    - Can only install one of: illuminate/notifications[5.7.x-dev, v6.20.41].
    - Can only install one of: illuminate/notifications[6.x-dev, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.0.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.0.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.0.2, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.0.3, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.0.4, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.1.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.10.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.11.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.12.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.13.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.13.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.14.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.15.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.15.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.16.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.17.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.17.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.10, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.11, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.12, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.13, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.14, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.15, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.16, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.17, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.18, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.19, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.2, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.20, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.21, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.22, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.23, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.24, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.25, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.26, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.27, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.28, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.29, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.3, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.30, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.31, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.32, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.33, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.34, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.35, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.36, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.37, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.38, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.39, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.4, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.40, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.41, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.42, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.43, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.5, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.6, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.7, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.8, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.18.9, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.19.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.19.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.2.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.10, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.11, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.12, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.13, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.14, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.15, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.16, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.17, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.18, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.19, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.2, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.20, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.21, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.22, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.23, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.24, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.25, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.26, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.27, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.28, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.29, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.3, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.30, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.31, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.32, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.33, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.34, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.35, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.36, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.37, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.38, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.39, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.4, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.40, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.41, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.5, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.6, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.7, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.8, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.20.9, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.3.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.4.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.5.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.5.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.5.2, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.6.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.6.1, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.6.2, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.7.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[v6.8.0, 5.7.x-dev].
    - Can only install one of: illuminate/notifications[5.7.x-dev, v6.20.41].
    - Conclusion: install illuminate/notifications 5.7.x-dev
    - Installation request for illuminate/notifications ^6.0 -> satisfiable by illuminate/notifications[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.27, v6.18.28, v6.18.29, v6.18.3, v6.18.30, v6.18.31, v6.18.32, v6.18.33, v6.18.34, v6.18.35, v6.18.36, v6.18.37, v6.18.38, v6.18.39, v6.18.4, v6.18.40, v6.18.41, v6.18.42, v6.18.43, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.19.0, v6.19.1, v6.2.0, v6.20.0, v6.20.1, v6.20.10, v6.20.11, v6.20.12, v6.20.13, v6.20.14, v6.20.15, v6.20.16, v6.20.17, v6.20.18, v6.20.19, v6.20.2, v6.20.20, v6.20.21, v6.20.22, v6.20.23, v6.20.24, v6.20.25, v6.20.26, v6.20.27, v6.20.28, v6.20.29, v6.20.3, v6.20.30, v6.20.31, v6.20.32, v6.20.33, v6.20.34, v6.20.35, v6.20.36, v6.20.37, v6.20.38, v6.20.39, v6.20.4, v6.20.40, v6.20.41, v6.20.5, v6.20.6, v6.20.7, v6.20.8, v6.20.9, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].


Installation failed, reverting ./composer.json to its original content.
```

I think it is because of this versioning in `composer.json`
```
"illuminate/notifications": "5.5.* || 5.6.* || 5.7.* || 5.8.* || 6.0.* || 7.0.*",
"illuminate/support": "5.5.* || 5.6.* || 5.7.* || 5.8.* || 6.0.* || 7.0.*"
```
Here I think it should be `"illuminate/notifications": "5.5.*|5.6.*|5.7.*|5.8.*|^6.0|^7.0"`

**Comment by akkivarma** [comment]
My `composer.json` file is as below:
```
{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.2",
        "guzzlehttp/guzzle": "^7.2",
        "illuminate/mail": "^6.0",
        "illuminate/notifications": "^6.0",
        "laravel/lumen-framework": "^6.0",
    },
    "require-dev": {
        "fakerphp/faker": "^1.13",
        "mockery/mockery": "^1.3",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "optimize-autoloader": true,
    "config": {
        "sort-packages": true
    }
}
```

**Comment by vrajroham** [comment]
Checking

**Comment by vrajroham** [comment]
@akkivarma Fixed in [V2.0.0](https://github.com/vrajroham/laravel-flock-notification/releases/tag/v2.0.0)

**Comment by akkivarma** [comment]
Hi @vrajroham , Thanks for looking into this but the new v2 version didn't fixed this issue. I am still getting the same error. For now I have created a custom flock channel.
